AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CodeCommit source example


Parameters:

  CodeCommitRepoName:
    Type: String

  CodeCommitBranch:
    Type: String


Resources:

  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Ref CodeCommitRepoName

  ArtifactStoreBucket:
    Type: AWS::S3::Bucket

  # See http://docs.aws.amazon.com/codepipeline/latest/APIReference/API_ActionTypeId.html
  # http://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#action-requirements
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Location: !Ref ArtifactStoreBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: PullCodeCommit
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration:
                RepositoryName: !GetAtt CodeCommitRepo.Name
                BranchName: !Ref CodeCommitBranch
                # AWS CodePipeline uses CloudWatch Events to detect changes in CodeCommit if polling is set to false
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: !Sub ${AWS::StackName}-Source
              RunOrder: 1

  # http://docs.aws.amazon.com/codepipeline/latest/userguide/iam-identity-based-access-control.html
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        # No logging policy. Seems CodePipeline does not log to CloudWatch Logs
        - PolicyName: read-write-artifactstore-bucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub '${ArtifactStoreBucket.Arn}/*'
        - PolicyName: pull-codecommit
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:UploadArchive
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:CancelUploadArchive
                Resource: !GetAtt CodeCommitRepo.Arn


Outputs:

  CodeCommitArn:
    Description: CodeCommit ARN
    Value: !GetAtt CodeCommitRepo.Arn