AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: S3 source example


Parameters:

  # AWS CodePipeline requires a versioned source/bucket for source stages
  S3Bucket:
    Type: String

  S3ObjectKey:
    Type: String


Resources:

  ArtifactStoreBucket:
    Type: AWS::S3::Bucket

  # See http://docs.aws.amazon.com/codepipeline/latest/APIReference/API_ActionTypeId.html
  # http://docs.aws.amazon.com/codepipeline/latest/userguide/reference-pipeline-structure.html#action-requirements
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Location: !Ref ArtifactStoreBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: SourceUploadToS3
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                S3Bucket: !Ref S3Bucket
                S3ObjectKey: !Ref S3ObjectKey
              OutputArtifacts:
                - Name: !Sub ${AWS::StackName}-Source
              RunOrder: 1

  # http://docs.aws.amazon.com/codepipeline/latest/userguide/iam-identity-based-access-control.html
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
        # No logging policy. Seems CodePipeline does not log to CloudWatch Logs
        - PolicyName: read-source-bucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Resource:
                  - !Sub 'arn:aws:s3:::${S3Bucket}'
                  - !Sub 'arn:aws:s3:::${S3Bucket}/*'
        - PolicyName: read-write-artifactstore-bucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub '${ArtifactStoreBucket.Arn}/*'
        